#:schema node_modules/wrangler/config-schema.json
name = "questions-api"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

route = { pattern = "questionsapi.connorbray.net", custom_domain = true }

[[kv_namespaces]]
binding = "KV"
id = "c34461be11934c728953e25ae619220e"
preview_id = "e888f254900c4c42979c7025b137760a"

[triggers]
crons = ["0 0 * * *"]
