#:schema node_modules/wrangler/config-schema.json
name = "questions"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "KV"
id = "c34461be11934c728953e25ae619220e"